// react/src/components/PostForm.jsx
import React, { useState } from 'react'
import MyButton from './UI/button/MyButton'
import MyInput from './UI/input/MyInput'

const PostForm = ({ create }) => {
    const [post, setPost] = useState({ title: '' ,body: '' })

    const addNewPost = (event) => {
        event.preventDefault()

        const newPost = { ...post, id: Date.now() }
        create(newPost)
        setPost({ title: '' ,body: '' })
    }

    return (
        <form className='post-form'>
            <MyInput
                value={post.title}
                onChange={event => setPost({ ...post, title: event.target.value })}
                type='text'
                placeholder='Название'
            /> 
            <MyInput
                value={post.body}
                onChange={event => setPost({ ...post, body: event.target.value })}
                type='text'
                placeholder='Описание'
            />
            <MyButton onClick={addNewPost}>Создать пост</MyButton>
      </form>
    )
}

export default PostForm

// vue/src/components/PostForm.vue
<template>
    <form @submit.prevent>
        <h4>Создание поста</h4>
        <my-input
            v-focus
            v-model:value="post.title"
            placeholder="Название"
        />
        <my-input
            v-model:value="post.body"
            placeholder="Описание"
        />
        <my-button @click="createPost">Создать</my-button>
    </form>
</template>

<script>
export default {
    data() {
        return {
            post: {
                title: '',
                body: ''
            }
        }
    },
    methods: {
        createPost() {
            this.post.id = Date.now()
            this.$emit('create', this.post)
            this.post = {
                title: '',
                body: ''
            }
        }
    }
}
</script>

<style scoped>
form {
    display: flex;
    flex-direction: column;
    gap: 15px;
}

</style>
